# Generated by Django 4.0.6 on 2022-09-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_cobrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crearcobro',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='interes',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='pagodeuda',
            options={'ordering': ('id',)},
        ),
    ]
