# Generated by Django 4.0.6 on 2022-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_cobrar', '0002_alter_crearcobro_options_alter_interes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interes',
            name='tasa',
            field=models.IntegerField(default=10),
        ),
    ]
